print("Первый интерва:")
hours_1=int(input("Введите часы: "))
minuts_1=int(input("Введите минуты: "))
seconds_1=int(input("Введите секунды: "))
print("Второй интервал: ")
hours_2=int(input("Введите часы: "))
minuts_2=int(input("Введите минуты: "))
seconds_2=int(input("Введите секунды: "))
print("Разность в секундах: ", 3600*(hours_2-hours_1)+60*(minuts_2-minuts_1)+(seconds_2-seconds_1))